name: 'Notion to markdown'
description: 'Convert notion files to markdown'
author: '@olinelson'
inputs:
  NOTION_API_KEY:
    required: true
  NOTION_DATABASE_ID:
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
